# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowsAviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Aviso(object):
    def setupUi(self, Aviso):
        Aviso.setObjectName("Aviso")
        Aviso.resize(432, 404)
        self.frame = QtWidgets.QFrame(Aviso)
        self.frame.setGeometry(QtCore.QRect(0, 0, 431, 401))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.543, y1:0, x2:0.541, y2:1, stop:0.300766 rgba(11, 255, 240, 255), stop:1 rgba(68, 0, 127, 255));\n"
"\n"
"border-radius:20px;\n"
"border:1px solid #00007f;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(150, 50, 141, 121))
        self.label_4.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("images/warning2.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.LbQuestion = QtWidgets.QLabel(self.frame)
        self.LbQuestion.setGeometry(QtCore.QRect(130, 200, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.LbQuestion.setFont(font)
        self.LbQuestion.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 75 22pt \"Arial\";\n"
"border:none")
        self.LbQuestion.setScaledContents(False)
        self.LbQuestion.setObjectName("LbQuestion")
        self.BtnBoxAvisoYes = QtWidgets.QPushButton(self.frame)
        self.BtnBoxAvisoYes.setGeometry(QtCore.QRect(100, 280, 100, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.BtnBoxAvisoYes.setFont(font)
        self.BtnBoxAvisoYes.setAcceptDrops(False)
        self.BtnBoxAvisoYes.setStyleSheet("QPushButton{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"border:5px solid #ffffff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"border:5px solid #0000f;\n"
"}")
        self.BtnBoxAvisoYes.setObjectName("BtnBoxAvisoYes")
        self.BtnBoxAvisoNo = QtWidgets.QPushButton(self.frame)
        self.BtnBoxAvisoNo.setGeometry(QtCore.QRect(240, 280, 100, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.BtnBoxAvisoNo.setFont(font)
        self.BtnBoxAvisoNo.setStyleSheet("QPushButton{\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"border:5px solid #ffffff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"border:5px solid #0000f;\n"
"}")
        self.BtnBoxAvisoNo.setObjectName("BtnBoxAvisoNo")

        self.retranslateUi(Aviso)
        QtCore.QMetaObject.connectSlotsByName(Aviso)

    def retranslateUi(self, Aviso):
        _translate = QtCore.QCoreApplication.translate
        Aviso.setWindowTitle(_translate("Aviso", "Aviso"))
        self.LbQuestion.setText(_translate("Aviso", "¿Desea Salir?"))
        self.BtnBoxAvisoYes.setText(_translate("Aviso", "Yes"))
        self.BtnBoxAvisoNo.setText(_translate("Aviso", "No"))
